import React from 'react';
import { Link } from 'react-router-dom';

function NoticePage() {
  return (
<div class="Questionnaire">
<div class="Block Headline Centered">Notice</div>
<div class="Block Subhead Centered" id="PageDescription">Please review the following notice for all Brighteon.AI models</div>

<div class="Text" id="PageArticle">
<p>All LLMs (Large Language Models) generate content based on the probabilistic relationships between words and phrases, word positions, punctuation and other semantic markers. This process is best described as &quot;dreaming&quot; a stream of words that seem to fit with the words that were either present in the prompt or generated previous to the current word. As a result, all LLMs are capable of generating content which is not accurate, but which &quot;sounds&quot; right in the same way that a dream might seem real, even though things you see in the dream might break the laws of physics (or the appearance of reality). </p>
<p>This LLM is provided solely as an experimental generative text engine for research purposes. It is your responsibility to check the factual correctness of any generated text produced by the model. Do not pursue important decisions involving medicine, finances, law, relationships, elections, investments or other areas based solely on content generated by any LLM. Do not use LLMs as replacements for qualified, professional guidance. </p>
<p>This LLM is provided as-is, without warranty, in a non-commercial, non-profit, open source effort to provide research tools to others who may advance the state of the art for LLM data science. Use at your own risk.</p>
</div>

</div>
  );
}

export default NoticePage;
