export const TYPE = {
  input: 'input',
  checkbox: 'checkbox',
  textarea: 'textarea',
  dropdown: 'dropdown',
};

export const dataFormStructure = [
  {
    key: 'planner',
    id: 1,
    title: 'Daily Meal Planner',
    subTitle:
      'Fill out the form below and Enoch AI will create a meal plan based the provided information.',
    fields: [
      {
        label: 'Dietary Preferences',
        promptText: 'Dietary Preferences',
        key: 'Dietary Preferences',
        default: '',
        questionLabel: 'List any preferences you have for the types of meals you prefer.',
        helperText:
          'Example: Vegan, vegetarian, keto, pescatarian, gluten-free, low sodium, high protein, paleo, organic.',
        type: TYPE.input,
      },
      {
        label: 'Weight Goals',
        promptText: 'Weight Goals',
        key: 'Weight Goals',
        default: '',
        questionLabel: 'List any weight loss goals you have or a target calorie range.',
        helperText: 'Example: Maintain weight, lose weight, gain weight, 1800 calories per day.',
        type: TYPE.input,
      },
      {
        label: 'Height & Weight',
        promptText: 'Height & Weight',
        key: 'Height & Weight',
        default: '',
        questionLabel:
          'List your current height and weight so Enoch can calculate accurate calorie needs.',
        helperText: 'Example: 5\'8", 160 lbs',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Allergies/Restrictions',
        promptText: 'Allergies/Restrictions',
        key: 'Allergies/Restrictions',
        default: '',
        questionLabel: 'List any allergies or any food restrictions you must avoid.',
        helperText: 'Example: Nuts, dairy, shellfish, soy, lactose',
        type: TYPE.input,
      },
      {
        label: 'Preferred Meal Frequency',
        promptText: 'Preferred Meal Frequency',
        key: 'Preferred Meal Frequency',
        default: '',
        questionLabel: 'List how often you prefer to eat each day (24-hours).',
        helperText: 'Example: 3 meals + 2 snacks, intermittent fasting windows',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Cooking Time/Effort',
        promptText: 'Cooking Time/Effort',
        key: 'Cooking Time/Effort',
        default: '',
        questionLabel: 'List the type of effort and time you prefer to put into cooking.',
        helperText: 'Example: Quick 15-minute meals, meal prep-friendly, no-cook options',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Favorite Cuisines or Ingredients',
        promptText: 'Favorite Cuisines or Ingredients',
        key: 'Favorite Cuisines or Ingredients',
        default: '',
        questionLabel: 'List some of your favorite types of meals, ingredients, etc.',
        helperText: 'Example: Mediterranean, Asian, comfort food, avocado, quinoa',
        type: TYPE.input,
      },
      {
        label: 'Dislikes/Avoidances',
        promptText: 'Dislikes/Avoidances',
        key: 'Dislikes/Avoidances',
        default: '',
        questionLabel: 'List any types of foods or ingredients you prefer not to consume.',
        helperText: 'Example: Mushrooms, spicy food, processed sugars',
        type: TYPE.input,
      },
    ],
  },
  {
    key: 'grocery',

    id: 2,
    title: 'Grocery Shopping Coach',
    subTitle:
      'Fill out the form below and Enoch AI will create a tailored shopping list that supports your health goals, dietary needs, budget, and lifestyle.',
    fields: [
      {
        label: 'Primary Health Goals',
        promptText: 'Primary Health Goals',
        key: 'Primary Health Goals',
        default: '',
        questionLabel: 'Select at least 3 health goals from the list below.',
        helperText: '',
        listCheckBoxes: [
          'Cardiovascular Health',
          'Brain Health',
          'Joint Health',
          'Digestive Health',
          'Immune System Support',
          'Bone Density Improvement',
          'Skin Health',
          'Lung Function Enhancement',
          'Vision Care',
          'Blood Sugar Regulation',
          'Weight Management',
          'Stress Reduction',
          'Sleep Improvement',
          'Hormonal Balance',
          'Muscle Strength Development',
          'Endurance Building',
          'Hydration Habits',
          'Nutritional Balance',
          'Cholesterol Management',
          'Blood Pressure Control',
          'Dental Health',
          'Hair & Scalp Care',
          'Mental Resilience',
          'Flexibility & Mobility',
          'Energy Level Optimization',
          'Kidney Health',
          'Liver Function Support',
          'Heart Rate Maintenance',
          'Metabolism Improvement',
          'Emotional Well-being',
        ],
        type: TYPE.checkbox,
        isRequired: true,
      },
      {
        label: 'Allergies/Restrictions',
        promptText: 'Allergies/Restrictions',
        key: 'Allergies/Restrictions',
        default: '',
        questionLabel: 'List any allergies or any food restrictions you must avoid.',
        helperText: 'Example: Nuts, dairy, shellfish, soy, lactose.',
        type: TYPE.input,
      },
      {
        label: 'Budget Range',
        promptText: 'Budget Range',
        key: 'Budget Range',
        default: '',
        questionLabel: 'List a budget you can apply towards groceries.',
        helperText: 'This will help determine the types of products/services recommended',
        type: TYPE.dropdown,
        options: [
          'Select a budget...',
          '$50 or less',
          '$50-100',
          '$100-200',
          '$200-500',
          'No Limit',
        ],
        isRequired: true,
      },
      {
        label: 'Shopping Constraints',
        promptText: 'Shopping Constraints',
        key: 'Shopping Constraints',
        default: '',
        questionLabel:
          'List any possible constraints you have on the type of foods you have access to.',
        helperText:
          'Example: Small refrigerator, shops primarily at Costco, prefers 15-minute trips.',
        type: TYPE.input,
      },
      {
        label: 'Cooking Habits',
        promptText: 'Cooking Habits',
        key: 'Cooking Habits',
        default: '',
        questionLabel: 'List the type of effort and time you prefer to put into cooking.',
        helperText: 'Example: No oven, 20-minute meals, hate chopping veggies.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Current Supplements/Medications',
        promptText: 'Current Supplements/Medications',
        key: 'Current Supplements/Medications',
        default: '',
        questionLabel:
          'List any medications or supplements you are currently taking to avoid any possible interactions.',
        helperText: 'Example: Blood thinners, iron supplements.',
        type: TYPE.input,
      },
      {
        label: 'Foods to Avoid or Crave Less',
        promptText: 'Foods to Avoid or Crave Less',
        key: 'Foods to Avoid or Crave Less',
        default: '',
        questionLabel: 'List any types of foods, or ingredients you prefer not to consume.',
        helperText: 'Example: Sugar, Mushrooms, potatoes, spicy foods.',
        type: TYPE.input,
      },
    ],
  },
  {
    key: 'finder',
    id: 3,
    title: 'Natural Supplements & Ingredients Finder',
    subTitle:
      'Fill out the form below and Enoch AI will create a personalized ingredient and supplement recommendations tailored towards your health goals.',
    fields: [
      {
        label: 'Primary Health Goals',
        promptText: 'Primary Health Goals',
        key: 'Primary Health Goals',
        name: 'primaryHealthGoals',
        default: [],
        questionLabel: 'Select at least 3 health goals from the list below.',
        helperText: '',
        listCheckBoxes: [
          'Cardiovascular Health',
          'Brain Health',
          'Joint Health',
          'Digestive Health',
          'Immune System Support',
          'Bone Density Improvement',
          'Skin Health',
          'Lung Function Enhancement',
          'Vision Care',
          'Blood Sugar Regulation',
          'Weight Management',
          'Stress Reduction',
          'Sleep Improvement',
          'Hormonal Balance',
          'Muscle Strength Development',
          'Endurance Building',
          'Hydration Habits',
          'Nutritional Balance',
          'Cholesterol Management',
          'Blood Pressure Control',
          'Dental Health',
          'Hair & Scalp Care',
          'Mental Resilience',
          'Flexibility & Mobility',
          'Energy Level Optimization',
          'Kidney Health',
          'Liver Function Support',
          'Heart Rate Maintenance',
          'Metabolism Improvement',
          'Emotional Well-being',
        ],
        type: TYPE.checkbox,
        isRequired: true,
      },
      {
        label: 'Allergies/Restrictions',
        promptText: 'Allergies/Restrictions',
        key: 'Allergies/Restrictions',
        default: '',
        questionLabel: 'List any allergies or any food restrictions you must avoid.',
        helperText: 'Example: Nuts, dairy, shellfish, soy, lactose.',
        type: TYPE.input,
      },
      {
        label: 'Current Supplements/Medications',
        promptText: 'Current Supplements/Medications',
        key: 'Current Supplements/Medications',
        default: '',
        questionLabel:
          'List any medications or supplements you are currently taking to avoid any possible interactions.',
        helperText: 'Example: Blood thinners, iron supplements.',
        type: TYPE.input,
      },
      {
        label: 'Lifestyle Factors',
        promptText: 'Lifestyle Factors',
        key: 'Lifestyle Factors',
        default: '',
        questionLabel: 'Describe below your current lifestyle.',
        helperText:
          'Example: Sedentary, frequently exercise, rarely exercise, smoker, frequent traveler.',
        type: TYPE.input,
        isRequired: true,
      },
    ],
  },
  {
    key: 'wellness',
    id: 4,
    title: 'Personalized Wellness Plan',
    subTitle:
      'Fill out the form below and Enoch AI will design a holistic, tailored wellness strategy that aligns with your goals, lifestyle, and unique needs.',
    fields: [
      {
        label: 'Primary Wellness Goals',
        promptText: 'Primary Wellness Goals',
        key: 'Primary Wellness Goals',
        default: '',
        questionLabel: 'Select at least 3 - 5 wellness goals from the list below',
        helperText: '',
        listCheckBoxes: [
          'Weight Management',
          'Stress Reduction',
          'Improved Sleep Quality',
          'Muscle Strength/Endurance',
          'Mental Resilience',
          'Cardiovascular Health',
          'Flexibility/Mobility',
          'Nutritional Balance',
          'Chronic Condition Management',
          'Energy Optimization',
          'Hormonal Balance',
          'Other',
        ],
        type: TYPE.checkbox,
        isRequired: true,
      },
      {
        label: 'Other Goals',
        promptText: 'Other Goals',
        key: 'Other Goals',
        default: '',
        questionLabel: "If you checked 'Other' in the previous step, describe it here.",
        helperText: 'Example: Clear skin, improve vision.',
        type: TYPE.input,
      },
      {
        label: 'Age Range',
        promptText: 'Age Range',
        key: 'Age Range',
        default: '',
        questionLabel: 'What age range do you currently fall into?',
        helperText: 'This will better help determine a wellness strategy',
        type: TYPE.dropdown,
        options: [
          'Select a range...',
          '15-20',
          '20-30',
          '30-40',
          '40-50',
          '50-60',
          '60-70',
          '70-80',
          '80+',
        ],
        isRequired: true,
      },
      {
        label: 'Height & Weight',
        promptText: 'Height & Weight',
        key: 'Height & Weight',
        default: '',
        questionLabel:
          'List your current height and weight so Enoch can calculate accurate calorie needs.',
        helperText: 'Example: 5\'8", 160 lbs.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Allergies/Restrictions',
        promptText: 'Allergies/Restrictions',
        key: 'Allergies/Restrictions',
        default: '',
        questionLabel: 'List any allergies or any food restrictions you must avoid.',
        helperText: 'Example: Nuts, dairy, shellfish, soy, lactose.',
        type: TYPE.input,
      },
      {
        label: 'Current Health Challenges',
        promptText: 'Current Health Challenges',
        key: 'Current Health Challenges',
        default: '',
        questionLabel: 'List below any health challenges you are currently experiencing.',
        helperText: 'Example: Arthritis, high blood pressure, menopause, prediabetes.',
        type: TYPE.input,
      },
      {
        label: 'Current Supplements/Medications',
        promptText: 'Current Supplements/Medications',
        key: 'Current Supplements/Medications',
        default: '',
        questionLabel:
          'List any medications or supplements you are currently taking to avoid any possible interactions.',
        helperText: 'Example: Blood thinners, iron supplements.',
        type: TYPE.input,
      },
      {
        label: 'Physical Limitations',
        promptText: 'Physical Limitations',
        key: 'Physical Limitations',
        default: '',
        questionLabel: 'List any physical limitations that impact your wellness routine.',
        helperText: 'Example: Knee pain, asthma, osteoporosis.',
        type: TYPE.input,
      },
      {
        label: 'Dietary Preferences',
        promptText: 'Dietary Preferences',
        key: 'Dietary Preferences',
        default: '',
        questionLabel: 'List any preferences you have for the types of meals you prefer.',
        helperText:
          'Example: Vegan, vegetarian, keto, pescatarian, gluten-free, low sodium, high protein, paleo, organic.',
        type: TYPE.input,
      },
      {
        label: 'Exercise Routine',
        promptText: 'Exercise Routine',
        key: 'Exercise Routine',
        default: '',
        questionLabel:
          'Describe below your current exercise routine and any physical limitations you may have.',
        helperText: 'Example: Walking, yoga, tennis, bike riding.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Sleep Routine',
        promptText: 'Sleep Routine',
        key: 'Sleep Routine',
        default: '',
        questionLabel: 'Describe your average hours of sleep a night and any current challenges.',
        helperText: 'Example: 7 hours, Insomnia, wake up multiple times a night.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Stress',
        promptText: 'Stress',
        key: 'Stress',
        default: '',
        questionLabel: 'Describe any major stressors and current coping strategies.',
        helperText: 'Example: Exercise, meditation, journaling.',
        type: TYPE.input,
      },
      {
        label: 'Social Routine',
        promptText: 'Social Routine',
        key: 'Social Routine',
        default: '',
        questionLabel:
          'Describe how many hours you spend with family/friends, on hobbies, or having fun.',
        helperText: 'Example: 1 hour a day, 8 hours a week, 2-3 hours every day.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Wellness Time',
        promptText: 'Wellness Time',
        key: 'Wellness Time',
        default: '',
        questionLabel: 'Describe your current daily time available for wellness activities.',
        helperText: 'Example: 15 minutes, 1 hour, 3 hours.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Budget Range',
        promptText: 'Budget Range',
        key: 'Budget Range',
        default: '',
        questionLabel:
          'Enter a budget you can apply towards gym memberships, wellness products, and services.',
        helperText: 'This will help determine the types of products/services recommended',
        type: TYPE.dropdown,
        isRequired: true,
        options: [
          'Select a budget...',
          '$50 or less',
          '$50-100',
          '$100-200',
          '$200-500',
          'No Limit',
        ],
      },
      {
        label: 'Work Type/Schedule',
        promptText: 'Work Type/Schedule',
        key: 'Work Type/Schedule',
        default: '',
        questionLabel: 'Describe your current job and the hours you work during the day or night.',
        helperText: 'Example: Desk job, 9-5.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Preferred Wellness Tracking',
        promptText: 'Preferred Wellness Tracking',
        key: 'Preferred Wellness Tracking',
        default: '',
        questionLabel: 'Describe your preferred way to track your wellness progress.',
        helperText: 'Example: Phone app, journal, wearable device.',
        type: TYPE.input,
      },
      {
        label: 'Accountability',
        promptText: 'Accountability',
        key: 'Accountability',
        default: '',
        questionLabel:
          'Describe your preferred way to hold yourself accountable for wellness progress.',
        helperText: 'Example: Solo, coach, friends, online community.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Obstacles',
        promptText: 'Obstacles',
        key: 'Obstacles',
        default: '',
        questionLabel:
          'Describe your biggest obstacles that have or could prevent you from reaching your wellness goals.',
        helperText: 'Example: Lack of time, motivation slumps, injuries.',
        type: TYPE.input,
      },
    ],
  },
  {
    id: 5,
    key: 'gardener',
    title: 'Master Gardener',
    subTitle:
      'Fill out the form below and Enoch AI will provide advice/techniques for sustainable gardening practices.',
    fields: [
      {
        label: 'Location',
        promptText: 'Location',
        key: 'Location',
        default: '',
        questionLabel: 'First, where are you located (city/region/country)?',
        helperText: 'Example: Austin/Texas/USA',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Climate',
        promptText: 'Climate',
        key: 'Climate',
        default: '',
        questionLabel:
          "What's your local climate like? If you know your USDA Hardiness Zone, share that too.",
        helperText: 'Example: Humid Subtropical',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Gardening Goals',
        promptText: 'Gardening Goals',
        key: 'Gardening Goals',
        default: '',
        questionLabel: 'What do you want to grow—veggies, flowers, herbs, or something else?',
        helperText: 'Example: Mix of vegetables and herbs',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Gardening Priority',
        promptText: 'Gardening Priority',
        key: 'Gardening Priority',
        default: '',
        questionLabel: 'Is your priority fresh food, beauty, helping pollinators, or a mix?',
        helperText: 'Example: Mix of fresh food and pollinators',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Available Space',
        promptText: 'Available Space',
        key: 'Available Space',
        default: '',
        questionLabel: 'What kind of space are you working with? Backyard, balcony, or windowsill?',
        helperText: 'Example: Small backyard',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Setup',
        promptText: 'Setup',
        key: 'Setup',
        default: '',
        questionLabel: 'Roughly how much area do you have (e.g., square feet or number of pots)?',
        helperText: 'Example: 160 square feet',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Sunlight',
        promptText: 'Sunlight',
        key: 'Sunlight',
        default: '',
        questionLabel: 'How many hours of direct sunlight does your space get daily?',
        helperText: "If your garden area is indoors, choose 'None.'",
        type: TYPE.dropdown,
        options: [
          'Select an amount...',
          'None',
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10+',
        ],
        isRequired: true,
      },
      {
        label: 'Soil',
        promptText: 'Soil',
        key: 'Soil',
        default: '',
        questionLabel: 'Have you tested your soil? Share details like texture or pH if you can.',
        helperText: 'Example: No tests, silt soil',
        type: TYPE.input,
      },
      {
        label: 'Time',
        promptText: 'Time',
        key: 'Time',
        default: '',
        questionLabel: 'How much time can you spend gardening each week?',
        helperText: 'Example: 15 minutes a day',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Commitment',
        promptText: 'Commitment',
        key: 'Commitment',
        default: '',
        questionLabel:
          'Do you want low-maintenance plants or are you up for high-care/high-reward ones?',
        helperText: "If you like a good mix in your garden, choose 'Both.'",
        type: TYPE.dropdown,
        options: ['Select an option...', 'Low-maintenance', 'High-care/high-reward', 'Both'],
        isRequired: true,
      },
      {
        label: 'Budget Range',
        promptText: 'Budget Range',
        key: 'Budget Range',
        default: '',
        questionLabel: "What's your startup budget? (We'll keep it thrifty if needed)",
        helperText: 'This will help determine the types products recommended',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Tools',
        promptText: 'Tools',
        key: 'Tools',
        default: '',
        questionLabel: 'Do you have basic tools, or should we suggest DIY alternatives?',
        helperText: 'This will help determine the type of instructions provided',
        type: TYPE.dropdown,
        isRequired: true,
        options: ['Select an option...', 'Basic Tools', 'Suggest DIY Alternatives'],
      },
      {
        label: 'Experience Level',
        promptText: 'Experience Level',
        key: 'Experience Level',
        default: '',
        questionLabel: 'Are you new to gardening, or do you have some experience?',
        helperText: 'This will help determine the type of instructions provided',
        type: TYPE.dropdown,
        options: ['Select experience level...', 'Beginner', 'Intermediate', 'Professional'],
        isRequired: true,
      },
      {
        label: 'Skills',
        promptText: 'Skills',
        key: 'Skills',
        default: '',
        questionLabel: 'Any specific skills you want to learn, like composting or pest control?',
        helperText: 'Example: Pest control and weather protection techniques',
        type: TYPE.input,
      },
      {
        label: 'Sustainability',
        promptText: 'Sustainability',
        key: 'Sustainability',
        default: '',
        questionLabel: 'Do you want to garden organically or use rainwater harvesting?',
        helperText: 'This will help determine the type of instructions provided',
        type: TYPE.dropdown,
        options: ['Select an option...', 'Garden Organically', 'Rainwater Harvesting', 'Both'],
        isRequired: true,
      },
      {
        label: 'Attraction',
        promptText: 'Attraction',
        key: 'Attraction',
        default: '',
        questionLabel: 'Are you hoping to attract bees, butterflies, or birds?',
        helperText: 'This will help determine the type of instructions provided',
        type: TYPE.dropdown,
        options: ['Select an option...', 'None', 'Bees', 'Butterflies', 'Birds', 'All'],
        isRequired: true,
      },
      {
        label: 'Challenges',
        promptText: 'Challenges',
        key: 'Challenges',
        default: '',
        questionLabel: 'Any worries, like pests, poor soil, or limited space?',
        helperText: 'Example: Poor soil, crickets and rodents',
        type: TYPE.input,
      },
      {
        label: 'Past Struggles',
        promptText: 'Past Struggles',
        key: 'Past Struggles',
        default: '',
        questionLabel: 'Any past gardening struggles we should troubleshoot?',
        helperText: 'Example: Poor water drainage',
        type: TYPE.input,
      },
      {
        label: 'Tracking',
        promptText: 'Tracking',
        key: 'Tracking',
        default: '',
        questionLabel: 'How would you like to track progress? Journal, app, or photos?',
        helperText: 'Example: App and Photos',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Adjustments',
        promptText: 'Adjustments',
        key: 'Adjustments',
        default: '',
        questionLabel: 'Are you open to adjusting your plan as seasons change or plants grow?',
        helperText: 'This will help determine the type of instructions provided',
        type: TYPE.dropdown,
        options: ['Select an option...', 'Yes', 'No'],
        isRequired: true,
      },
    ],
  },
  {
    id: 6,
    key: 'longevity',
    title: 'Longevity Roadmap',
    subTitle:
      'Fill out the form below and Enoch AI will provide a 12-month plan with age-specific tips to help you reach your longevity goals.',
    fields: [
      {
        label: 'Age Range',
        promptText: 'Age Range',
        key: 'Age Range',
        default: '',
        questionLabel: 'What age range do you currently fall into?',
        helperText: 'This will better help determine a wellness strategy',
        type: TYPE.dropdown,
        isRequired: true,
        options: [
          'Select a range...',
          '15-20',
          '20-30',
          '30-40',
          '40-50',
          '50-60',
          '60-70',
          '70-80',
          '80+',
        ],
      },
      {
        label: 'Current Health Challenges',
        promptText: 'Current Health Challenges',
        key: 'Current Health Challenges',
        default: '',
        questionLabel: 'List below any health challenges you are currently experiencing.',
        helperText: 'Example: Arthritis, high blood pressure, menopause, prediabetes.',
        type: TYPE.input,
      },
      {
        label: 'Primary Aging-Related Goals',
        promptText: 'Primary Aging-Related Goals',
        key: 'Primary Aging-Related Goals',
        default: '',
        questionLabel: 'Select at least 5 goals from the list below.',
        helperText: '',
        listCheckBoxes: [
          'Joint/Mobility Health',
          'Cognitive Sharpness',
          'Heart Health',
          'Bone Density',
          'Skin Elasticity',
          'Energy/Stamina',
          'Vision/Hearing Care',
          'Hormonal Balance',
          'Sleep Quality',
          'Stress Resilience',
        ],
        min: 5,
        isRequired: true,
        type: TYPE.checkbox,
      },
      {
        label: 'Longevity Priorities',
        promptText: 'Longevity Priorities',
        key: 'Longevity Priorities',
        default: '',
        questionLabel: 'Describe what you are hoping to achieve with your longevity.',
        helperText:
          'Example: "Stay active with grandkids," "Prevent cognitive decline," "Maintain independence."',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Allergies/Restrictions',
        promptText: 'Allergies/Restrictions',
        key: 'Allergies/Restrictions',
        default: '',
        questionLabel: 'List any allergies or any food restrictions you must avoid.',
        helperText: 'Example: Nuts, dairy, shellfish, soy, lactose.',
        type: TYPE.input,
      },
      {
        label: 'Exercise',
        promptText: 'Exercise',
        key: 'Exercise',
        default: '',
        questionLabel:
          'Describe below your current exercise routine and any physical limitations you may have.',
        helperText: 'Example: Walking, yoga, tennis, bike riding.',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: 'Current Supplements/Medications',
        promptText: 'Current Supplements/Medications',
        key: 'Current Supplements/Medications',
        default: '',
        questionLabel:
          'List any medications or supplements you are currently taking to avoid any possible interactions.',
        helperText: 'Example: Blood thinners, iron supplements.',
        type: TYPE.input,
      },
      {
        label: 'Budget Range',
        promptText: 'Budget Range',
        key: 'Budget Range',
        default: '',
        questionLabel: 'Enter a budget you can apply towards supplements and wellness products.',
        helperText: 'This will help determine the types products recommended',
        type: TYPE.dropdown,
        isRequired: true,
        options: [
          'Select a budget...',
          '$50 or less',
          '$50-100',
          '$100-200',
          '$200-500',
          'No Limit',
        ],
      },
    ],
  },
  {
    id: 7,
    key: 'journals',
    title: 'Simplify Scientific Journals',
    subTitle:
      'Supply the text of a science journal/paper and Enoch AI will break it down into clear, accessible language for non-experts.',
    fields: [
      {
        label: 'Journal Text',
        promptText: 'Journal Text',
        key: 'Journal Text',
        default: '',
        questionLabel: 'Type or copy/paste the text of the journal in the text box below.',
        helperText: '',
        type: TYPE.textarea,
        isRequired: true,
      },
    ],
  },
  {
    id: 8,
    key: 'summarizer',
    title: 'Enoch Text Summarizer',
    subTitle: 'Type or copy/paste the text to summarize in the text box below.',
    fields: [
      {
        label: 'Summary Length',
        promptText: 'Summary Length',
        key: 'Summary Length',
        default: '',
        questionLabel: 'Select how long the final summary should be.',
        helperText: '',
        type: TYPE.dropdown,
        options: [
          'Choose a length...',
          '1 sentence',
          '1 paragraph',
          '2-3 paragraphs',
          '3-5 paragraphs',
          '5-10 paragraphs',
        ],
        isRequired: true,
      },
      {
        label: 'What would you like to summarize?',
        promptText: 'What would you like to summarize?',
        key: 'What would you like to summarize?',
        default: '',
        questionLabel: '',
        helperText: 'Note: The longer the text, the longer it may take to complete a summary.',
        type: TYPE.textarea,
        isRequired: true,
      },
    ],
  },
  {
    id: 9,
    key: 'Ingredient',
    title: 'Ingredient Checker',
    subTitle: 'Fill out the form below and Enoch AI will provide a summary of the ingredient.',
    fields: [
      {
        label: 'Enter an Ingredient Name',
        promptText: 'Ingredient',
        key: 'Ingredient Name',
        default: '',
        questionLabel: 'Type or copy/paste the ingredient in the text box below.',
        helperText: 'Example: Phosphate, canola oil, riboflavin, folic acid',
        type: TYPE.input,
        isRequired: true,
      },
      {
        label: ' What Would You Like to Know?',
        promptText: 'Tell me',
        key: 'feeling',
        default: '',
        questionLabel:
          'Enoch will tell you about the characteristic of the ingredient based on your selection.',
        helperText: 'Example: Arthritis, high blood pressure, menopause, prediabetes.',
        type: TYPE.dropdown,
        options: [
          'Choose an option...',
          `What's good about it`,
          `What's bad about it`,
          `What's good and bad about it`,
        ],
        isRequired: true,
      },
    ],
  },
];
